import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-[calc(100vh-64px)] bg-[#030303] text-gray-300 p-6 md:p-12 pb-24 font-sans selection:bg-red-500/30">
      <div className="max-w-3xl mx-auto space-y-8 mt-12 md:mt-0">
        <h1 className="text-4xl font-black text-white">Terms of Service</h1>
        <p className="text-sm text-gray-500">Last updated: May 2026</p>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">1. Acceptance of Terms</h2>
          <p>By accessing or using Leakage Tracker (the "Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">2. Description of Service</h2>
          <p>Leakage Tracker is an AI-powered expense tracking application that integrates with WhatsApp and Telegram. We utilize artificial intelligence (Google Gemini) to analyze your spending habits, categorize transactions, and provide financial insights or "roasts".</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">3. User Accounts & Data</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>You must register with a valid email address and optionally link your WhatsApp/Telegram number.</li>
            <li>You are responsible for maintaining the security of your account.</li>
            <li>You grant us permission to process the text messages you send to our bots solely for the purpose of tracking your expenses and generating AI responses.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">4. Prohibited Uses</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>Use the service for any illegal or unauthorized purpose.</li>
            <li>Attempt to hack, destabilize, or abuse the API or webhooks.</li>
            <li>Spam or overwhelm the AI systems. We employ rate limiting to prevent abuse.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-white">5. Limitation of Liability</h2>
          <p>Leakage Tracker is provided "as is" for entertainment and informational purposes. The AI financial "roasts" and advice are generated by artificial intelligence and do not constitute professional financial advice. We are not liable for any financial losses or damages resulting from the use of this service.</p>
        </section>

        <div className="pt-8 border-t border-white/10">
          <Link href="/" className="text-red-500 hover:text-red-400 font-bold">
            ← Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
}
